services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: ./backend
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb:27017}
      - MONGO_DB=${MONGO_DB:-demo_db}
      - MONGO_COLLECTION=${MONGO_COLLECTION:-documents}
      - API_PORT=${API_PORT:-8000}
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE:-http://localhost:8000/api}
    ports:
      - "5173:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mongo-data:


